### PR TITLE
Amendment to #3223 + slight cleanup

### PR DESCRIPTION
**Pull request by ricksterhd123**
I tested #3223 and it passed on my PC so I wanted to be sure that it wasn't just me. I think the error in #3223 stemmed from the use of template literals in `pug/test/cases-es2015/attr.pug` so I've added a new test case which tests them. I've also removed two variables which weren't being used in two test files. 

Didn't know how to add commit in that PR so I had to open a new one.

### CODE REVIEW

**Comment by ricksterhd123** [comment]
```
PS C:\Users\anon\Desktop\pug> npm test

> pug-monorepo@ pretest C:\Users\anon\Desktop\pug
> lerna run pretest

lerna notice cli v3.10.8
lerna info versioning independent
lerna info Executing command in 1 package: "yarn run pretest"
lerna info run Ran npm script 'pretest' in 'pug-runtime' in 2.3s:
yarn run v1.22.4
$ npm run prepublish

> pug-runtime@2.0.5 prepublish C:\Users\anon\Desktop\pug\packages\pug-runtime
> node prepublish

Done in 1.74s.
lerna success run Ran npm script 'pretest' in 1 package in 2.3s:
lerna success - pug-runtime

> pug-monorepo@ test C:\Users\anon\Desktop\pug
> jest







 PASS  packages/pug-lexer/test/check-lexer-functions.test.js



 PASS  packages/pug-error/test/index.test.js

 PASS  packages/pug-runtime/test/index.test.js


 PASS  packages/pug-walk/test/index.test.js


 PASS  packages/pug-strip-comments/test/index.test.js  


 PASS  packages/pug-attrs/test/index.test.js


 PASS  packages/pug-linker/test/index.test.js


 PASS  packages/pug/test/error.reporting.test.js (6.215s)

 PASS  packages/pug-filters/test/filter-aliases.test.js


 PASS  packages/pug/test/eachOf/index.test.js


(node:8820) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

 PASS  packages/pug/test/pug.test.js (7.243s)


 PASS  packages/pug-load/test/index.test.js


 PASS  packages/pug-lexer/test/index.test.js


 PASS  packages/pug/test/run-syntax-errors.test.js

 PASS  packages/pug-filters/test/per-filter-options-applied-to-nested-filters.test.js


 PASS  packages/pug/test/extends-not-top-level/index.test.js


 PASS  packages/pug-filters/test/index.test.js        


 PASS  packages/pug-parser/test/index.test.js



 PASS  packages/pug/test/regression-2436/index.test.js



 PASS  packages/pug/test/markdown-it/index.test.js

 PASS  packages/pug/test/examples.test.js
 PASS  packages/pug-parser/test/no-unnecessary-blocks.test.js
 PASS  packages/pug/test/shadowed-block/index.test.js
 PASS  packages/pug/test/run-es2015.test.js
 PASS  packages/pug/test/duplicate-block/index.test.js
 PASS  packages/pug/test/run.test.js (6.206s)

Test Suites: 26 passed, 26 total
Tests:       646 passed, 646 total
Snapshots:   326 passed, 326 total
Time:        16.625s
Ran all test suites.
PS C:\Users\anon\Desktop\pug> node -v
v12.16.2
```

**Comment by ricksterhd123** [comment]
mkdirp is incompatible with earlier versions of node, i'll leave it there

**Comment by ricksterhd123** [comment]
Might need to decide whether to continue support for node 6  and node 8 since mkdirp 0.5.1 supports >= 8 and 1.0.4 supports >= 10. I've removed node version 6 from travis because I'm sure by now it's deprecated and node 8 has reached/reaching it's EOL. LTS version is 12.16.3 so I switched that for version 12, and added version 14 which is latest.

**Comment by ForbesLindesay** [comment]
Thanks for the contribution. This has now been done via another PR.

**Pull request closed without merging**
