### PR TITLE
Omit optional HTML5 tags

### PR DESCRIPTION
**Pull request by jart**
See: https://www.w3.org/TR/html5/syntax.html#optional-tags

### CODE REVIEW

**Comment by jart** [comment]
Here's a good reference implementation of the standard if you want to make your HTML generator omit the optional tags. https://github.com/bazelbuild/rules_closure/commit/6c5cbe3d51ccebe0f47ec207280533f2e80d1142

**Comment by ForbesLindesay** [comment]
I think it is better if we generate all the optional tags. It makes our output easier to understand and more consistent.

**Comment by jart** [comment]
It's so much harder to understand HTML if you have to read through all that superfluous opening and closing tag boilerplate.

Now that I've brought to your attention that a more elegant output format exists, and provided you with an Apache 2.0 licensed implementation you can loosely copy, will you decline to implement the more concise, succinct, and elegant solution?

**Comment by ForbesLindesay** [comment]
Yes, I will.

**Pull request closed without merging**
