### PR TITLE
enhance stdin

### PR DESCRIPTION
**Pull request by yorkie**

### CODE REVIEW

**Comment by TimothyGu** [comment]
To be honest, the correct way to do terminate input is through the "^D" escape code, which means "EOF". Allowing for "^C" is a hack.

**Comment by vendethiel** [comment]
(this needs to be ^Z on windows)

**Comment by TimothyGu** [comment]
@vendethiel true but still.

**Comment by vendethiel** [comment]
I'm just saying — "if ^D goes through, please support ^Z"

**Comment by yorkie** [comment]
hmm, i didn't call `^D` or `^C` directly, actually we are doing a software based nodejs, and the `^` stuffs is controlled by nodejs :-(

moreover, this case in my opinion doesn't mean the real EOF of the progress, user just says he wouldn't input anything, so the control is on jade/nodejs. and when inputing `^D`, it ends the whole progress/process, rather than input session.

**Comment by TimothyGu** [comment]
@yorkie said:

> i didn't call `^D` or `^C` directly, and the `^` stuffs are controlled by nodejs :-(

It doesn't matter. `spawnedProc.stdin.emit('end')` Fast 'n' easy. Compared to `SIGINT` which you'll need to do `spawnedProc.kill('SIGINT')` with an unavoidingly ominous name.

> however when inputing `^D`, it ends the whole progress/process, rather than input session.

This is just plain wrong. `^C` means `SIGINT`, which ["terminal interrupt[s]"](http://pubs.opengroup.org/onlinepubs/009695399/basedefs/signal.h.html) the program. `^C` *should* end the whole process.

On the other hand, `^D`/EOF/closing `stdin` is terminating the input stream, not the whole process.

**Pull request merged**
