### PR TITLE
Update website URL

### PR DESCRIPTION
**Pull request by TimothyGu**
:tada: :tada: :tada:

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
🎉🎉🎉🎉

@tj Can you update jade-lang.com to redirect to pugjs.org please

**Comment by tj** [comment]
Sure thing! Is the pugjs one a gh-pages site? I don't think it'll work then if I change the DNS records since the Host will still be different

**Comment by tj** [comment]
Ah it's using Cloudflare haha, oops, maybe you have to map that domain? Let me know if you want the A records changed

**Comment by ForbesLindesay** [comment]
Could you update the nameservers? Then I can use a cloudflare rule to do the redirect.  I don't really want to run a VPS just do do the redirect and cloudflare is usually my goto for this kind of thing.

The new values should be:

 - ben.ns.cloudflare.com
 - kate.ns.cloudflare.com

jade nameservers

**Comment by tj** [comment]
updated!

**Comment by TimothyGu** [comment]
@ForbesLindesay, could you please set up the DNS rules?

**Comment by ForbesLindesay** [comment]
Done :)

**Comment by ForbesLindesay** [comment]
Might take a few hours for DNS to propagte.

**Comment by 0xcrypto** [comment]
Is http://jadelang.net/ associated? If you should redirect to pugjs.org

**Pull request merged**
