### PR TITLE
Short filter syntax

### PR DESCRIPTION
**Pull request by coderanger**
This branch adds a new syntax of "tag::filter text" for single-line invocation of a filter.

My primary use case for this would be translation and localization tooling, but some others that come to mind include rendering math forumla and controlling text escaping.

### CODE REVIEW

**Comment by tjconcept** [comment]
Is this in master? I can't find it anywhere in the docs. I'm considering it for i18n.

**Comment by ForbesLindesay** [comment]
The pull request never got updated.  If someone wants to submit fresh pull requests against pug-lexer we could probably consider merging it.

**Comment by TimothyGu** [comment]
It's already supported in current master (with a slightly different syntax):

```jade
tag: :markdown-it **bold**
```

```html
<tag><p><strong>bold</strong></p>
</tag>
```

**Comment by ForbesLindesay** [comment]
I think the thinking here is that we probably shouldn't require that space in this particular case.

**Pull request closed without merging**
